### ISSUE TITLE
Feature Request: Disable hyperlinks

### ISSUE THREAD

**Issue by zhujunmian** [ushnisha/tranquility-reader-webextensions#26]
Is it possible to request a feature, to disable all the hyperlinks in the page so to facilitate deep reading?

**Comment by ushnisha** [comment]
Thanks for the suggestion.  It is definitely an interesting idea.  It is possible to create another option to disable hyperlinks (default behavior will be to show hyperlinks as now).

But before implementing something like this, I have a few questions:

(1) What is the distracting part with the hyperlinks?  The color, or the underling or both?  Or is it the temptation of clicking on a link?

(2) I give an option to save the page as a PDF document.  The saved PDF document (created using functionality provided by webextensions API) does not have the hyperlinks saved (as links).  So, the chance for distraction reading this document is definitely lesser because clicking on the hyperlinked text will do nothing.

(3) If it is the color of the link that is causing the distraction, I already provide an option called "Link Color".  If that is set to the same value as the "Font Color" then you will not be distracted by the color -- the text may still be underlined, but that feels a lot less of distraction -- I tried it out and could feel the difference in the reading experience.

Do any of these solve the problem or is there something inherently problematic with the links that causes the distraction?  I would like to understand this better before making any code changes so that I can take these into consideration.  

If you have any suggestions that would preserve the links and minimize the distraction at the same time, that would be the best way to implement this option rather than simply disabling all the links.  The reason I feel strongly about this is that I suspect that once users have fine tuned the options of the extension, they rarely go back to customizing it frequently.  So, someone selecting the "deep reading" mode with links completely disabled/removed *may* lose out in the long term because they don't even realize there are some useful links with complementary/supplementary information.  Would like to know your thoughts on this.

**Comment by ushnisha** [comment]
Since there is no response to the questions about what kind of problems are caused or to the workarounds suggested, I will assume that the user has accepted one of the suggested workarounds (like printing to PDF) as the solution.  Closing this issue.  Please reopen with clarification/response to the questions posed if you still need such a feature.
