### ISSUE TITLE
remove headers from PDF generation

### ISSUE THREAD

**Issue by JR-Utily** [ushnisha/tranquility-reader-webextensions#28]
I want to use this plugin to generate pdf files from good articles I find on the web to read on my e-reader.
But when I click on the pdf button, the generated pdf includes headers even if my firefox print options already remove them.
It would be great not to have them to have a cleaner pdf generation (or at least to add an option in the preference to include them or not).

**Comment by ushnisha** [comment]
The header currently repeats information already available in the printed content (title & source link).  Removing it should not cause any problem, especially given than often this information is truncated because of width restrictions.

Providing controls to customize the header and footer settings is a bit more work and clutters up the current settings page;  other users might want to customize other page settings while printing a PDF and since there are over 20+ page settings that can be customized at this time; and this is going to require an entire settings page of its own.

Do you see any use for the footer information, or does that also interfere with the e-readers' pagination/processing?  Maybe a single option to include/exclude both header & footer simultaneously might be the easy solution.  Let me know if that works for you.

**Comment by ushnisha** [comment]
Adding a checkbox ends up being more work the way the code is setup now; rather than a checkbox, it is easier to add a select-option with 4 choices:  

"Both" --> include both header and footer
"Neither" --> include neither header nor footer
"Only Header" --> include only header
"Only Footer" --> include only footer

...will implement the above in the next release.

**Comment by ushnisha** [comment]
Fixed in version 3.0.22; option to select "Both", "Neither", "Only Header", and "Only Footer" is now available; default is current behaviour --> "Both".

In addition, the margins have been changed to 1.0" from the default value of 0.5" -- during testing of this new option, some of the page text was uncomfortably close to the header/footer; so margin has been increased for a more pleasing/readable experience.

**Comment by JR-Utily** [comment]
Thanks a lot !
