### ISSUE TITLE
Ability to hide options buttons

### ISSUE THREAD

**Issue by SublimeAnanas** [ushnisha/tranquility-reader-webextensions#33]
I mainly use Tranquility to read articles, but my incredibly annoying issue is whenever I select text any text on the page, the left and right arrows, as well as the top right buttons disappear, then reappear when unselecting the text.
They do this every time, which is quite distracting when you like to guide your reading by selecting text, or even just temporarily highlighting it.

My enhancement request would be an option to turn off the extension's buttons from showing, in particular all of the following:
-Left double arrow
-Right double arrow
-Tranquility preferences
-Original URL
-Save as PDF

![6ynfsIY](https://user-images.githubusercontent.com/100245457/155242249-b4851780-c33e-410f-a6a7-f3e62e14ebc8.png)

In case this isn't deemed an important/popular enough request, is there a way to stop these buttons from constantly flashing in/out when selecting text?

**Comment by ushnisha** [comment]
There are two ways to handle this:

(1) Provide an option that will allow users to hide these button.  Not everyone uses these buttons and if they click on an empty portion of the screen/document, these buttons pop up.  Default value of the option will continue to display them for backward compatibility, and users can disable this if they wish

(2) Another way of solving this problem is to detect if any text is selected, and not show these ui menu items if text is selected.  If no text is selected then show the ui menu items as we do currently.

Solution (2) solves this specific users request with minimal changes --> avoids adding yet another option.  And lesser code to add/maintain.  Need to decide of we implement only (2) or both (2) and (1).

**Comment by ushnisha** [comment]
Solution (2) will be implemented in 3.0.24.  If text is selected, then ui menu items will not be shown.  This is simpler and the code is easier to maintain.

**Comment by ushnisha** [comment]
Version 3.0.24 has been submitted and should soon be available as an update.

Now, when you select text, you will not see the ui related menu/control buttons appear.  After you have finished reading the selected text, please select the next block of text you want to read immediately without click elsewhere on the page.  

If you simply click on the screen that will un-select the selected/highlighted text and the ui related menu/control buttons will appear again.

Hopefully, this should be sufficient for your use case.  If there are any significant problems with this fix, please leave a comment and we can use this same issue to address it.  

If everything works as expected, I will close the issue after a couple of weeks of testing time.

**Comment by SublimeAnanas** [comment]
You're awesome, thank you. Will give feedback once I tested it.

**Comment by ushnisha** [comment]
Closing issue... assuming user has tested it and is satisfied with the fix.
