### ISSUE TITLE
Eliminating Graphics

### ISSUE THREAD

**Issue by HoudyDoody** [ushnisha/tranquility-reader-webextensions#43]
Is there a way to have Tranquility suppress graphics on a page? I've had too many pages come out of Tranquility that seem alright but then print with the graphic, usually an ad, taking up a full page.

**Comment by ushnisha** [comment]
Please check the extension options/preferences page.  Under the "text and image display preferences", there is an option to "Hide Images".  
It takes 3 values:
(1) never (always shows images); 
(2) always (always hides images);
(3) hide_only_for_print (shows images when reading, but hides images when printing to a pdf through the extension

Let me know if this works for you; if not, please provide a sample page/url that does not work correctly so that I can see if there is a bug in how this optino is implemented.

**Comment by ushnisha** [comment]
Closing issue since there is no further feedback from the user.  Assuming that the explanation provided earlier was sufficient.
