### ISSUE TITLE
Why does it require "Access your data for all websites" permission?

### ISSUE THREAD

**Issue by rpattabi** [ushnisha/tranquility-reader-webextensions#6]
This extension works fantastic. Thank you. However, I'm concerned about permissions.

Is "Access your data for all websites" permission required? As per [mozilla doc](https://support.mozilla.org/kb/permission-request-messages-firefox-extensions#w_access-your-data-for-all-websites), this means that this extension can access **data entered into web pages, such as usernames and passwords**.

I thought accessing URL should be enough, which I believe is available from [Access browser tabs](https://support.mozilla.org/ta/kb/permission-request-messages-firefox-extensions#w_access-browser-tabs).

**Comment by ushnisha** [comment]
Thanks for the issue and sorry about the delayed response; due to some mail forwarding issues, I was not receiving email notifications of new issues opened on github.

When a page is transformed by the extension, clicking on a link in the transformed view will take you to the new url and also automatically transform that page content also to make it readable.  It does all of this in the same/original/active tab.  Since the original/active tab still has its URL pointed to the old URL, only the contents of the page are from the new link.

To the best of my understanding, with just the activeTab permission, I can only retrieve pages that are from the same domain; I will need the "<all_urls>" permission to make an XMLHttpRequest to content from other domains (CORS request restrictions).  However, the "all_urls" permission will also trigger the alarming warning message you see.  I cannot remove the "all_urls" permission without also losing functionality/backward compatibility.

If you have any thoughts on how to do this without any additional action from the users (or forcing the opening on links in new tabs) do let me know and I can make the changes if that will work without change in behaviour of the extension or loss of functionality.

**Comment by ushnisha** [comment]
Closing the issue since there is no way to workaround this permission request.  The issue has also been reviewed as part of the "recommended extensions" process and if there was an alternate solution, the reviewers would have advised suitably.
